### PR TITLE
please_cli: Use skopeo to push docker images

### LINKED ISSUE #1335: pushing multi layer docker image fails
[push](https://github.com/garbas/push/) was a quick hack to get this functionality working. meanwhile other more reliable tools were created that we can use for this task, [skopeo](https://github.com/projectatomic/skopeo).

instruction how can skopeo be used with nix is [here](https://discourse.nixos.org/t/push-docker-tgz-images-to-registry-directly/189)

### PR DESCRIPTION
**Pull request by rail**
Closes #1335

This PR replaces the unmaintained push Python library with
[skopeo](https://github.com/projectatomic/skopeo). At the same time it
unifies the deployment methods pushing docker images to docker
registries.

### CODE REVIEW

**Comment by garbas** [comment]
@rail looks like i didn't create taskcluster role for testing branch

**Comment by rail** [comment]
@La0 your input is appreciated

**Comment by La0** [comment]
I'll test on Monday

Le ven. 3 août 2018 à 16:14, Rail Aliiev <notifications@github.com> a
écrit :

**Comment by garbas** [comment]
@La0 it pushes the image directly to heroku docker registry in case of target HEROKU. in case of TASKCLUSTER_HOOK and DOCKERHUB target we push to https://hub.docker.com/r/mozillareleng/services/tags/

**Comment by La0** [comment]
Oh right ! So it's all good.

**Comment by rail** [comment]
Yay! thank you for taking care of the PR.

**Pull request merged**
