### PR TITLE
Bug 1492033 - partner repacks should be enabled for ESR60

### PR DESCRIPTION
**Pull request by nthomas-mozilla**
I'm still working on other parts of bug 1492033 but wanted to get this up for comment. We'll need partner repacks on for b8 and higher, release, and esr, which I've expressed as not b1-b7.

### CODE REVIEW

**Comment by nthomas-mozilla** [comment]
What do you think @rail ?

**Comment by rail** [comment]
It should just work. I wonder if it would be easier to read (esp. for the future) if you explicitly return True for the is_esr case.

**Comment by nthomas-mozilla** [comment]
OK, I've force pushed to handle rebasing onto the tip of master and combining all commits into a single one. This PR also does a few more things than initially - adds an is_eme_free_enabled function because we don't want to turn that on for ESR, includes tests for that and is_partner_enabled, fixes up my flake8 errors.

Would you be able to run your eye over this again @rail, and also push it to the staging branch ? I don't have permissions to push.

**Comment by rail** [comment]
Staging is locked ATM, probably in preparation for the tomorrow's release. We can try again tomorrow.

**Comment by nthomas-mozilla** [comment]
The gecko changes are on inbound and I'll uplift to esr60 if they don't bounce, so I'll be ready to merge this real soon. What processes should I be aware of for landing and deployment ?

**Comment by rail** [comment]
The regular release process is documented [here](https://docs.mozilla-releng.net/deploy/regular.html), but we can deploy it off of the master branch on demand as well.

**Comment by rail** [comment]
I just pushed it to staging. I'd wait ~30 minutes after https://tools.taskcluster.net/groups/YolkC7_pTQyTx_xBZUOkeQ is done to let dockerflow pick up the changes.

**Comment by nthomas-mozilla** [comment]
Woo, and it works starting up promote at ZRbK0I7aTPOoyuxr1izy3w. Going to try closing/reopening this PR to get Github to rerun taskcluster (which passed but the message got lost somewhere).

**Comment by nthomas-mozilla** [comment]
This is ready to go, except I'm not sure why the 'Taskcluster (pull request)' status stays pending, rather than swapping to complete after the two tasks complete.

**Comment by nthomas-mozilla** [comment]
Thanks!

**Pull request merged**
