### PR TITLE
shipit-workflow: sync releases from v1

### PR DESCRIPTION
**Pull request by rail**
This is still a WIP (a working prototype). I appreciate some feedback on this.

This change add 2 things:

  * fetch releases from ship-it v1 (fetch_v1.py). This has to be done
    behind VPN, usnig real credentials, thus the code is not a part
    of the main app.

  * use the generated JSON files with releases to update the v2 DB with
    old releases. We use these data to generate partial suggestions at
    least. The code assumes that the JSON files lives under `src/shipit_workflow/scripts/`

### CODE REVIEW

**Comment by rail** [comment]
We should land #1369 before running this for reals.

**Comment by garbas** [comment]
TODO to get this done:
 - make fetch_v1 a flask subcommand
 - protect sync endpoint

**Comment by garbas** [comment]
@rail I did the changes described in previous comment. can you review the changes I made?

**Comment by rail** [comment]
LGTM

**Comment by rail** [comment]
I cannot approve, because I initiated the PR.

**Pull request merged**
