### PR TITLE
please_cli: Changed name parameter of 'click.group' to show correct output (#1071)

### PR DESCRIPTION
**Pull request by rv404674**
Changed name param of 'click.group' so that `./please --help` does not show `.please-wrapper`.

### CODE REVIEW

**Comment by garbas** [comment]
@rv404674 did you check the output of `./please --help`? since even with your patch this still shows `Usage: .please-wrapper ...`

**Comment by rv404674** [comment]
@garbas, you are right. It still shows 
"rahul (pleaseCliTypo) release-services $ ./please --help
Usage: .please-wrapped [OPTIONS] COMMAND [ARGS]...
........
"

when i chaned the '__init__.py' to show the change that should happen after i changed some code. What steps should i follow.????
'just ./please run project' ???

**Comment by rv404674** [comment]
hey @garbas , little bit help. I am now able to figure it out.

**Comment by garbas** [comment]
@rv404674 when you do any change in `lib/please_cli` you only need to run `./please --help` and wait a little so that new please_cli gets built. This is how you can test this.

I would also suggest to try to override command name in an example you create. eg:

```python

import click

@click.group(name="crazy")
def crazy():
    click.echo('Am I cray?')

@crazy.command()
def yes():
    click.echo('Yes')

@crazy.command()
def no():
    click.echo('No')

if __name__ == '__main__':
    crazy()
```

**Comment by rv404674** [comment]
hey @garbas, i have been trying from multiple days - read about decorators and also official click documentation, have also tried to change some parameters and  then check whether it is working as required. But still i am not able to solve this, can you give me a hint.

**Comment by rv404674** [comment]
hey @garbas thanks. It worked. :)
screenshot from 2018-10-10 11-45-18

**Pull request merged**
