### PR TITLE
staticanalysis/bot: Slightly improve the clang-format patch URL message.

### PR DESCRIPTION
**Pull request by jankeromnes**
Using the suggestion from #1271 (and also swapping the diff URL and the bug report URL).

### CODE REVIEW

**Comment by jankeromnes** [comment]
Failed with:

```
    def _on_request(self, adapter, request, **kwargs):
        match = self._find_match(request)
        resp_callback = self.response_callback
        if match is None:
            if request.url.startswith(self.passthru_prefixes):
                logger.info(
                    'request.allowed-passthru', extra={
                        'url': request.url,
                    })
                return _real_send(adapter, request)
            error_msg = 'Connection refused: {0} {1}'.format(
                request.method, request.url)
            response = ConnectionError(error_msg)
            response.request = request
            self._calls.add(request, response)
            response = resp_callback(response) if resp_callback else response
>           raise response
E           requests.exceptions.ConnectionError: Connection refused: POST http://phabricator.test/api/transaction.search
/nix/store/m166rp4fnbmsphgv9p1csvzpsjy3kl7b-python3.6-responses-0.9.0/lib/python3.6/site-packages/responses.py:543: ConnectionError
```

**Comment by jankeromnes** [comment]
Note: I mocked the http://phabricator.test/api/transaction.search API response, using the response to a https://phabricator-dev.allizom.org/api/transaction.search call for a random revision with few comments in it.

**Comment by jankeromnes** [comment]
It failed with:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/nix/store/fmnk6agpwbig2fdywrlbpd556k7459vh-python3.6-mozilla-static-analysis-bot-1.0.0/lib/python3.6/site-packages/static_analysis_bot/report/phabricator.py:50: in publish
    for issue in issues
/nix/store/fmnk6agpwbig2fdywrlbpd556k7459vh-python3.6-mozilla-static-analysis-bot-1.0.0/lib/python3.6/site-packages/static_analysis_bot/report/phabricator.py:50: in <listcomp>
    for issue in issues
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <static_analysis_bot.report.phabricator.PhabricatorReporter object at 0x7fffe653d7b8>
revision = PHID-DIFF-abcdef
issue = <conftest.mock_issues.<locals>.MockIssue object at 0x7fffe653dfd0>
existing_comments = []
    def comment_inline(self, revision, issue, existing_comments=[]):
        '''
            Post an inline comment on a diff
            '''
        assert isinstance(revision, PhabricatorRevision)
>       assert isinstance(issue, Issue)
E       AssertionError
/nix/store/fmnk6agpwbig2fdywrlbpd556k7459vh-python3.6-mozilla-static-analysis-bot-1.0.0/lib/python3.6/site-packages/static_analysis_bot/report/phabricator.py:79: AssertionError
```

**Comment by jankeromnes** [comment]
Failed with:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <static_analysis_bot.report.phabricator.PhabricatorReporter object at 0x7fffe65664e0>
issues = [<conftest.mock_issues.<locals>.MockIssue object at 0x7fffe6566390>, <conftest.mock_issues.<locals>.MockIssue object at 0x7fffe65662b0>, <conftest.mock_issues.<locals>.MockIssue object at 0x7fffe65668d0>]
bug_report_url = 'https://bit.ly/2IyNRy2', diff_url = None, max_comments = None
    def build_comment(self, issues, bug_report_url, diff_url=None, max_comments=None):
        '''
            Build a human readable comment about published issues
            '''
        def pluralize(word, nb):
            assert isinstance(word, str)
            assert isinstance(nb, int)
            return '{} {}'.format(nb, nb == 1 and word or word + 's')
        # Calc stats for issues, grouped by class
        stats = self.calc_stats(issues)
        # Build parts depending on issues
        defects, analyzers = [], []
        for cls, cls_stats in stats.items():
            part = COMMENT_PARTS.get(cls)
            assert part is not None, \
>               'Unsupported issue class {}'.format(cls)
E           AssertionError: Unsupported issue class <class 'conftest.mock_issues.<locals>.MockIssue'>
/nix/store/pixm6yzxyjpdqhfr3bv8jybr9ck30p27-python3.6-mozilla-static-analysis-bot-1.0.0/lib/python3.6/site-packages/static_analysis_bot/report/base.py:121: AssertionError
```

**Comment by jankeromnes** [comment]
So I need to import `MockIssue` in `static_analysis_bot/report/base.py`, but it doesn't seem to be exported in `tests/conftest.py`.

**Comment by La0** [comment]
@jankeromnes Actually that's the opposite, you need `MockIssue` to be an instance of `Issue`.
So import `Issue` into `tests/conftest.py`

**Comment by jankeromnes** [comment]
@La0 I did that already. The newest failure is:

```
./static_analysis_bot/report/base.py:30:5: F821 undefined name 'MockIssue'
```

And I'm not sure how to import `MockIssue` in `base.py`.

**Comment by jankeromnes** [comment]
From IRC:

> 18:23:00 bastien> janx: for your PR it would make your life a lot easier if you created some dummy ClangTidyIssue instead of using MockIssue
> 18:23:48 bastien> janx: for example https://github.com/mozilla/release-services/blob/bdb2fce4f89b50c18f97acd454b9392cb53f9e07/src/staticanalysis/bot/tests/test_clang.py#L47

**Comment by jankeromnes** [comment]
What? How did this succeed? Seems like it didn't hit my assert.

**Pull request merged**
