### PR TITLE
Deploying v46 (and bumping version to v47)

### PR DESCRIPTION
**Pull request by garbas**
This Pull Request contains the version bump and should be merged once deployment is successful.
Deployment coordinator for this release is: @garbas

# Deployment to staging

- Build1 -> https://tools.taskcluster.net/groups/Ea30l_KFQOG6LMTYIEF3sg
- Build2 -> https://tools.taskcluster.net/groups/DKl97ku0Qo6CQ1VlR1G4ag

## Verifications

- [x] shipit-pulse-listener
- [x] releng-mapper
- [x] releng-tokens
- [x] releng-treestatus
- [x] releng-frontend
- [x] releng-docs
- [x] releng-notification-identity
- [x] releng-notification-policy
- [x] releng-tooltool
- [x] staticanalysis/frontend
- [x] staticanalysis/bot [*](https://github.com/mozilla/release-services/pull/1496#issuecomment-420940887)
- [x] codecoverage/backend
- [x] codecoverage/crawler
- [x] codecoverage/bot
- [x] uplift/frontend
- [x] uplift/backend
- [x] uplift/bot
- [x] shipit/frontend
- [x] shipit/api

# Deployment to production

- Build 1 -> https://tools.taskcluster.net/task-group-inspector/#/Hv8Xmu-ARcOomfCUtg4cNw

## Verifications

- [x] codecoverage/backend
- [x] codecoverage/bot
- [x] codecoverage/crawler
- [x] releng-docs
- [x] releng-frontend
- [x] releng-mapper
- [x] releng-notification-identity
- [x] releng-notification-policy
- [x] releng-tokens
- [x] releng-tooltool
- [x] releng-treestatus
- [x] shipit-pulse-listener
- [x] shipit/api
- [x] staticanalysis/bot
- [x] staticanalysis/frontend
- [x] uplift/backend
- [x] uplift/bot
- [x] uplift/frontend

### CODE REVIEW

**Comment by jankeromnes** [comment]
Three issues with the `staticanalysis/bot` currently on staging:

- [ ] when trying to analyze Java files, `./mach configure` fails: `checking for java... not found\n 0:08.38 ERROR: The program java was not found.  Set $JAVA_HOME to your Java SDK directory or use \'--with-java-bin-path={java-bin-dir}\'` https://tools.taskcluster.net/groups/erd59wAJTbiioVjx0dFj_A/tasks/erd59wAJTbiioVjx0dFj_A/runs/0/logs/public%2Flogs%2Flive.log#L38
- [ ] after successfully analyzing our previous defects patch, the bot fails to apply some diff: `AssertionError('Generated patch /tmp/tmp4v642njv.diff application failed on /cache/sa-unified/js/src/jsapi.cpp',))` https://tools.taskcluster.net/groups/em4GrnJ0RF6CojHJTaeirg/tasks/em4GrnJ0RF6CojHJTaeirg/runs/0/logs/public%2Flogs%2Flive.log
- [ ] when the base revision is unknown (e.g. a Git commit SHA), it doesn't fall back to mozilla-central: `static_analysis_bot.AnalysisException: Failed to update to revision cc1e0fcf1da6f8265bbe809ea0795ee67780cdb4` https://tools.taskcluster.net/groups/G8KYkj7iT--ZtHfHP_fGVg/tasks/G8KYkj7iT--ZtHfHP_fGVg/runs/0/logs/public%2Flogs%2Flive.log#L59

**Comment by La0** [comment]
@jankeromnes Issue n°3 is solved with #1500 (please review)

**Comment by jankeromnes** [comment]
`staticanalysis/bot` now runs fine on staging, except it fails to submit all comments to Phabricator-dev because of: `Conduit API error ERR-CONDUIT-CORE : [Access Denied: D679] (Can Edit) You do not have permission to edit this object. // Members of the project "Restricted Project" can take this action. The owner of a revision can always view and edit it.`

We suspect that this may be a matter of giving proper access rights to the token we use, so it shouldn't block release.

Marking `staticanalysis/bot` as validated, because otherwise everything looks fine.

**Comment by La0** [comment]
Static analyis is now OK (see https://tools.taskcluster.net/groups/RtHNNMtdQj2TcO1tEOU7MA)

**Comment by La0** [comment]
@garbas 2 updates are needed on the production secret, in section `static-analysis-bot`:

1. Setup the phabricator credentials in a specific new key:
```
  PHABRICATOR:
    url: 'https://phabricator.services.mozilla.com/api/'
    api_key: api-XXXXXXX
```

2. `REPORTERS` should now be (no more credentials or mozreview):
```
  REPORTERS:
    - reporter: mail
      emails:
        - babadie@mozilla.com
        - sledru@mozilla.com
        - jan@mozilla.com
        - andi@mozilla.com
    - reporter: phabricator
```

**Comment by garbas** [comment]
marco: shipit-code-coverage should be replaced with codecoverage/bot, shipit-code-coverage-backend with codecoverage/backend and shipit-code-coverage-crawler with codecoverage/crawler
marco: shipit-pulse-listener should be updated to use "services-production-codecoverage/bot" instead of "services-production-shipit-code-coverage"

**Comment by La0** [comment]
@garbas Another secret update, for `code-coverage-*`, you need to rename :

* `codecoverage/bot` to `code-coverage-bot`
* `codecoverage/backend` to `code-coverage-backend`

**Comment by La0** [comment]
@garbas The production generic hook role needs a new scope, please add  `queue:get-artifact:project/gecko/android-*` to https://tools.taskcluster.net/auth/roles/hook-id%3Aproject-releng%2Fservices-production-*

**Comment by garbas** [comment]
@La0 secrets for codecoverage are updated and scope is added to the `hook-id:project-releng:services-production-*`

**Comment by jankeromnes** [comment]
Validating `staticanalysis/bot` with a bad patch worked, but I notice a few other failures in production:

- `AnalysisException('Failed to import target patch',)`: https://tools.taskcluster.net/groups/TSmPJBEoSjK0tuP3xIqI3Q
- `AnalysisException('Failed to import parent patch PHID-DIFF-gdcmdiq5qzufp3is5qzz',)`: https://tools.taskcluster.net/groups/TmKzrK_dTAOA7Ktqmg0DcA
- `AnalysisException('Failed to import target patch',)`: https://tools.taskcluster.net/groups/B_QBsg01TVKZDdfMQ3aXHA
- `AnalysisException('Failed to import parent patch PHID-DIFF-gdcmdiq5qzufp3is5qzz',)`: https://tools.taskcluster.net/groups/HrvYzEooTiep_udgwzIsug

From the 13 tasks that were triggered since the production update, 6 succeeded, 4 failed, and 3 are still running ("Started").

**Pull request merged**
