### PR TITLE
Deploying v47 (and bumping version to v48)

### PR DESCRIPTION
**Pull request by garbas**
This Pull Request contains the version bump and should be merged once deployment is successful.
Deployment coordinator for this release is: @garbas

# Deployment to staging

- Build1 -> https://tools.taskcluster.net/groups/RfXfYwymTkuQOLuDBLqvFw
- Build2 -> https://tools.taskcluster.net/groups/O8CPDxH4QWauA-WNIAHDgA
- Build3 -> https://tools.taskcluster.net/groups/aT-ycknwRyOg43kRY7_-mg

## Verifications

- [x] docs
- [x] codecoverage/backend
- [x] codecoverage/bot
- [x] codecoverage/crawler
- [x] pulselistener
- [x] releng-frontend
- [x] mapper/api
- [x] notification/identity
- [x] notification/policy
- [x] tokens/api
- [x] tooltool/api
- [x] treestatus/api
- [x] shipit/api
- [x] shipit/frontend
- [x] staticanalysis/bot
- [x] staticanalysis/frontend
- [x] uplift/backend
- [x] uplift/bot
- [x] uplift/frontend

# Deployment to production

- Build1 -> https://tools.taskcluster.net/task-group-inspector/#/HQNzVcWTQoibft5DavVR7A

## Verifications

- [x] docs
- [x] codecoverage/backend
- [x] codecoverage/bot
- [x] codecoverage/crawler
- [x] pulselistener
- [x] releng-frontend
- [x] mapper/api
- [x] notification/identity
- [x] notification/policy
- [x] tokens/api
- [x] tooltool/api
- [x] treestatus/api
- [x] shipit/api
- [x] shipit/frontend
- [x] staticanalysis/bot
- [x] staticanalysis/frontend
- [x] uplift/backend
- [x] uplift/bot
- [x] uplift/frontend

### CODE REVIEW

**Comment by La0** [comment]
@garbas When deploying on production, you'll need to update the Taskcluster secret, renaming the section `shipit-pulse-listener` to `pulselistener`.

**Comment by La0** [comment]
@garbas Could you add a trailing `/` to the production secret > `pulselistener` > `HOOKS` > `phabricator_url`

The end result must be: `phabricator_url: 'https://phabricator.services.mozilla.com/api/'`

**Comment by La0** [comment]
@marco-c The [code coverage task failed](https://tools.taskcluster.net/groups/WpJcolqSS2SwH7cK3kj4VQ/tasks/WpJcolqSS2SwH7cK3kj4VQ/runs/0/logs/public%2Flogs%2Flive.log), i'm not sure it's related to the release. Can you have a look ?

**Comment by marco-c** [comment]
> @marco-c The code coverage task failed, i'm not sure it's related to the release. Can you have a look ?

Yes, that failure is unrelated to the release.

**Comment by La0** [comment]
Waiting for [codecov to finish](https://tools.taskcluster.net/groups/RzasAxK6QgKildarYziGIw/tasks/RzasAxK6QgKildarYziGIw/runs/0/logs/public%2Flogs%2Flive.log), and then release is done

**Pull request merged**
