### PR TITLE
[WIP] uplift/bot: Push grafts to a remote mercurial repo (was #672)

### PR DESCRIPTION
**Pull request by jankeromnes**
Resuscitated #672 by manually re-applying all the changes. (*Phew!*)

Now on to finishing the work and testing it.

### CODE REVIEW

**Comment by jankeromnes** [comment]
Failed with:

> please_cli.check_cache: [Errno 2] No such file or directory: 'error: syntax error, unexpected CONCAT, at /tmp/release-services-364d5c3079522acaddcbe94cfe29b34387c23790/src/uplift/bot/default.nix:64:7' (exception='Traceback (most recent call last):\n  File "/nix/store/cdwahzkd7pc4srxykg3sycqpdbaxqa6l-python3.7-mozilla-please-cli-52/lib/python3.7/site-packages/please_cli/check_cache.py", line 101, in cmd\n    with open(drv) as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'error: syntax error, unexpected CONCAT, at /tmp/release-services-364d5c3079522acaddcbe94cfe29b34387c23790/src/uplift/bot/default.nix:64:7\'')

Also has a lot of `... NOT EXISTS`, whatever that means. :stuck_out_tongue:

**Comment by jankeromnes** [comment]
Now failed with:

> ./tests/conftest.py:21:1: E302 expected 2 blank lines, found 1
> ./uplift_bot/sync.py:8:1: I001 isort found an import in the wrong position
> ./uplift_bot/sync.py:19:1: F401 'uplift_bot.bugzilla.list_bugs' imported but unused
> ./uplift_bot/sync.py:26:1: I001 isort found an import in the wrong position
> ./uplift_bot/merge.py:4:1: I001 isort found an import in the wrong position
> ./uplift_bot/merge.py:5:1: I001 isort found an import in the wrong position
> ./uplift_bot/merge.py:6:1: I001 isort found an import in the wrong position
> ./uplift_bot/mercurial.py:206:13: E722 do not use bare 'except'

and:

>     def test_analysis_qs_approved():
>         '''
>         Check Bugzilla parameters building
>         for approved uplift requests
>         '''
> >       from shipit_uplift.models import BugAnalysis
> E       ModuleNotFoundError: No module named 'shipit_uplift'
> tests/test_analysis.py:146: ModuleNotFoundError

**Comment by jankeromnes** [comment]
Now it failed with:

> cli_common.command: __________________________________test_mail___________________________________
> cli_common.command: 
> cli_common.command: mock_taskcluster_credentials = None
> cli_common.command: 
> cli_common.command:     @responses.activate
> cli_common.command:     def test_mail(mock_taskcluster_credentials):
> cli_common.command:         '''
> cli_common.command:         Test uplift merge failures email report
> cli_common.command:         '''
> cli_common.command:         from uplift_bot.report import Report
> cli_common.command:         from uplift_bot.merge import MergeTest
> cli_common.command: 
> cli_common.command:         def _check_email(request):
> cli_common.command:             payload = json.loads(request.body)
> cli_common.command: 
> cli_common.command:             assert payload['subject'] == '[test] Uplift bot detected 2 merge failures to beta, esr52'
> cli_common.command:             assert payload['address'] == 'test@mozilla.com'
> cli_common.command:             assert payload['template'] == 'fullscreen'
> cli_common.command:             assert payload['content'].startswith('# Failed automated merge test')
> cli_common.command: 
> cli_common.command:             return (200, {}, '')  # ack
> cli_common.command: 
> cli_common.command:         # Add mock taskcluster email to check output
> cli_common.command:         responses.add_callback(
> cli_common.command:             responses.POST,
> cli_common.command:             'https://notify.taskcluster.net/v1/email',
> cli_common.command:             callback=_check_email,
> cli_common.command:         )
> cli_common.command: 
> cli_common.command:         report = Report(['test@mozilla.com'])
> cli_common.command: >       report.add_invalid_merge(MergeTest('123456', 'beta', []))
> cli_common.command: E       TypeError: __init__() missing 1 required positional argument: 'patches'
> cli_common.command: 
> cli_common.command: tests/test_report.py:36: TypeError

**Comment by jankeromnes** [comment]
Woohoo! All checks have passed! :heavy_check_mark: :tada:

**Comment by La0** [comment]
uplift/bot is down.

**Pull request closed without merging**
