### PR TITLE
cli_common: Don't declare RabbitMQ exchange, assume it already exists

### LINKED ISSUE #1779: Pulse listener is broken on staging because it can't access `exchange/taskcluster-queue/v1/task-group-resolved` exchange
aioamqp.exceptions.ChannelClosed: (403, "ACCESS_REFUSED - access to exchange 'exchange/taskcluster-queue/v1/task-group-resolved' in vhost '/' refused for user 'releng-services-staging'")

CC @La0

### PR DESCRIPTION
**Pull request by marco-c**
Fixes #1779.

Works locally, I'm testing it on staging.

### CODE REVIEW

**Comment by garbas** [comment]
I added this recently to ensure exchange exists. otherwise we need to send a pulse message. Also I did exactly what is writting in the docs. If we remove this our services wont start.

Do we have time to explore why this is happening?

**Comment by marco-c** [comment]
> Do we have time to explore why this is happening?

I can wait, but I'd need this on staging otherwise I can't be sure things are working (if pulse is broken, code coverage is not running at all).

**Comment by marco-c** [comment]
@garbas I'm going to merge this as it is risky to leave the bug in (someone might be pushing to staging and break pulse listener again). We can easily readd it back later and investigate more.

**Comment by garbas** [comment]
a script to reproduce this behavior is here https://paste.debian.net/1059410/

**Pull request merged**
