### PR TITLE
staticanalysis/bot: Document how to create and use your own secret.

### PR DESCRIPTION
**Pull request by jankeromnes**
Drive-by fix:

- docs: Remove duplicated rst docs after their projects got renamed.

### CODE REVIEW

**Comment by jankeromnes** [comment]
Note: the `src/docs/projects/shipit-*.rst` files I removed are duplicates (left over from project renaming I think).

However, I did run a diff for each file, to see if they had diverged. (Only `shipit-static-analysis.rst` had diverged from `staticanalysis-bot.rst`, and I ported my recent changes to the new file before deleting it.)

**Comment by garbas** [comment]
@jankeromnes it might make sense to merge all statisanalyses documentation in one file. i plan to do the same for other projects i work on. since those "sub"projects are more connected

**Comment by jankeromnes** [comment]
> it might make sense to merge all statisanalyses documentation in one file

Good idea! But let's leave that for a follow-up pull request.

**Comment by jankeromnes** [comment]
> could you remove all occurences of a famous first name by a more anonymous one (john) ?

Sure! Replaced all by `michel` (my go-to anonymous first name).

**Pull request merged**
