### PR TITLE
Use pytest tmpdir in mock_config(#1935)

### PR DESCRIPTION
**Pull request by rv404674**
Solves #1935

### CODE REVIEW

**Comment by La0** [comment]
@rv404674 Could you fix the [two linting errors](https://tools.taskcluster.net/groups/GBHXR_GsQIirjDpAprC_Iw/tasks/fOD1SebVQsG5hi1a70iq5g/runs/0/logs/public%2Flogs%2Flive.log#L2222) on the bot ? Thanks !

**Comment by rv404674** [comment]
hey @La0 . It is saying "No module named tempdir found", which is actually true. It is passed as arguement in a function whereever it is being used. ( i though it to be a import lib just like tempfile). So can you please tell how to use it then, i need to pass it as well?

**Comment by marco-c** [comment]
@rv404674 see the docs at https://docs.pytest.org/en/latest/tmpdir.html, tmpdir is not a module that you can import.

**Comment by rv404674** [comment]
hey @marco-c . Is this bug already solved by you.

**Comment by marco-c** [comment]
> hey @marco-c . Is this bug already solved by you.I am very sorry for taking such a long time.

I don't think I solved this bug, but you can check yourself (is the file still importing tempfile?).

**Comment by rv404674** [comment]
> > hey @marco-c . Is this bug already solved by you.I am very sorry for taking such a long time.
> 
> I don't think I solved this bug, but you can check yourself (is the file still importing tempfile?).

Yup it is. https://github.com/mozilla/release-services/blob/master/src/staticanalysis/bot/tests/conftest.py#L9

**Comment by La0** [comment]
Hello @rv404674,

Do you plan on finishing this pull request ? It needs rebase + fixing the issues reported by @marco-c .
No problem if you can't finish it !

**Comment by rv404674** [comment]
hey @La0 i do plan to finish this request. Will take a look on this one in Tuesday, but will finish "replace formating issue by today.

**Comment by rv404674** [comment]
hey @La0 can you please tell me how to solve this one. I am getting really confused on this one. I know it is an easy one but still i am not getting it.

**Comment by marco-c** [comment]
@rv404674 you'll need to read the docs I pointed you at. Maybe try to create a simple test file yourself where you use the feature so you get familiar with it, then come back to this once you know how to use it.

**Comment by La0** [comment]
You need to rebase on current master, solve merge conflicts, and fix the isort issues reported on [last build](./tests/conftest.py:17:1: I004 isort found an unexpected blank line in imports), then checks that all tests are passing

**Comment by rv404674** [comment]
> You need to rebase on current master, solve merge conflicts, and fix the isort issues reported on last build `./tests/conftest.py:17:1: I004 isort found an unexpected blank line in imports`, then checks that all tests are passing

**Comment by rv404674** [comment]
@La0 are the changes which i did correct. https://github.com/mozilla/release-services/pull/1937/files

**Comment by La0** [comment]
@rv404674 Why did you close this PR ?

**Pull request closed without merging**
