### PR TITLE
shipit_code_coverage: Use new elasticsearch cluster

### PR DESCRIPTION
**Pull request by gabriel-v**
closes https://github.com/mozilla/release-services/issues/1399

### CODE REVIEW

**Comment by gabriel-v** [comment]
I tested this on the testing branch and it works. Here's the task: https://tools.taskcluster.net/groups/EsRi5kU8Rt2bIirnpA22tA/tasks/EsRi5kU8Rt2bIirnpA22tA/details

After looking at the chunk mapping, I found the following issue: the count for the `file_to_test` table is exactly `360000`. It looks like our query limits for building this are too low. Opening a new issue about this.

**Comment by marco-c** [comment]
Is `run.suite.fullname` available on the old cluster too? I'm wondering if they are compatible. If they are, we should make the URL configurable via a secret.

**Comment by gabriel-v** [comment]
When running the updated query on the old cluster, it errors with: `run.suite.fullname does not exist in schema`.

The `run.suite` field switched from being a string to an object, so the old request can't work.

**Comment by marco-c** [comment]
OK, sounds like we have to switch to the new cluster completely then. Thanks for checking.

**Pull request merged**
