### PR TITLE
backend_common: add empty app_heartbeat

### LINKED ISSUE #1512: /__heartbeat__ failing with HTTP 500 in -dev
Screenshot: https://irccloud.mozilla.com/file/2alN0n0A/Screen%20Shot%202018-09-17%20at%2012.50.18%20PM.png

Cloudops uses `/__heartbeat__` to check a deployment was successful, so we need this to work. We can use `/docs` for now, but we'll need this fixed eventually.

cc @garbas

### PR DESCRIPTION
**Pull request by rail**
This should fix the issues like
```
AttributeError: module 'backend_common.log' has no attribute 'app_heartbeat'
```

Closes #1512

### CODE REVIEW

**Comment by rail** [comment]
I'm going to implement `app_heartbeat` for `log.py`, but it won't be doing anything. I'm not sure how to properly implement this, because logs are sent via UDP and there is no response to verify.

**Comment by garbas** [comment]
- for papertrail we can check at least if ip is reachable, maybe some other checks from their troubleshooting guide
- for sentry we can look for "ok" from https://sentry.prod.mozaws.net/_health/

**Comment by rail** [comment]
>     * for papertrail we can check at least if ip is reachable, maybe some other checks from their troubleshooting guide
> 
>     * for sentry we can look for "ok" from https://sentry.prod.mozaws.net/_health/

I'm going to file an issue to implement those. ATM this exception prevents us from deploying to production I believe.

**Comment by garbas** [comment]
:+1:

**Pull request merged**
