### PR TITLE
Update codespell to 1.14

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by jankeromnes** [comment]
@La0 my validation patches from https://github.com/jankeromnes/gecko-dev/commits/validate-reviewbot include a [codespell error](https://github.com/jankeromnes/gecko-dev/commit/1ec436edac823179ab3403fd9ef67ec07458c3f1#diff-ca54995346ef2a4bc4aa5c2c99a85c1aR7).

I'll push it to dev now.

**Comment by jankeromnes** [comment]
Pushed to https://phabricator-dev.allizom.org/D714 (`PHID-DIFF-frm7omwen4ubwkis4psc`).

**Comment by jankeromnes** [comment]
Note: The spelling mistake [was detected on staging last Friday](https://phabricator-dev.allizom.org/D714#26714) (even though `clang-tidy` didn't work). But that was one of the very first times that I ever saw `codespell` report anything via `./mach lint` (in my experience, it usually doesn't report any mistakes, and it's usually not even listed in the checkers in our dashboard).

So just a word of caution that, if the mistake is not reported post-update, it may not necessarily be the update's fault.

**Comment by La0** [comment]
After a rebase, that seems to work: 

```
codespell issue error browser/base/content/docs/tabbrowser/index.rst line 7
```

**Comment by jankeromnes** [comment]
:fireworks: :fireworks: :fireworks:

**Pull request merged**
