### PR TITLE
cli_common: reconnect on pulse errors

### LINKED ISSUE #827: Try to reconnect automatically to pulse server
The pulse server was shutdown on 2018-02-07, and pulse listener just stopped working, not trying to reconnect after the server went back up.

Error message in log:
```
aioamqp.protocol: Server closed connection: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', code=320, class_id=0, method_id=0
```

### PR DESCRIPTION
**Pull request by rail**
closes #827

### CODE REVIEW

**Comment by garbas** [comment]
:smile: i like the draft feature in github

**Comment by rail** [comment]
@La0 @garbas what do you think about this approach?

It doesn't reconnect, but at least it detects the issue and should exit, letting either heroku or kubernetes to restart the container.

We can probably wrap the function somehow so we reconnect, but I failed to do that properly for now. I may try and pursue this at some point.

**Comment by rail** [comment]
In eeac03f1c66675011f26719febe3ba0a0a1be281 I added some reconnect logic. it should work (TM), but I'm not sure what would be the best way to test it...

**Comment by La0** [comment]
You could test it with `mitmproxy` between you and the pulse service, kill the proxy for a while and restart it: the pulse listener should try to reconnect...

Thanks for this patch, it will be used on pulselistener a lot :+1:

**Comment by rail** [comment]
I actually have a real local rabbitmq server that I can use, was wondering which service I should try to emulate :)

**Comment by rail** [comment]
Let's try something that I know, shipit worker

**Comment by rail** [comment]
It worked fine locally.
* I tried the shipit worker without rabbitmq running. It keeps retrying until the server comes up and starts consuming messages afterwards.
* Killing the server keeps the worker running and retrying until the server comes up. The worker reconnects and starts consuming messages as expected.

I think this should just work. We should probably watch the consumers after this merged to production.

**Pull request merged**
