### PR TITLE
Coordinating deployment (v45) and bumping version to v46

### PR DESCRIPTION
**Pull request by garbas**
This Pull Request contains the version bump and should be merged once deployment is successful.
Deployment coordinator for this release is: @garbas

# Deployment to staging

https://tools.taskcluster.net/groups/AwrC9OzoTwm6_q0xZTIpmA

## Staging QA

- [x] releng-docs (@garbas)
- [x] releng-frontend (@garbas)
- [x] releng-mapper (@garbas)
- [x] releng-notification-identity (@garbas)
- [x] releng-notification-policy (@garbas)
- [x] releng-tokens (@garbas)
- [x] releng-tooltool (@garbas)
- [x] releng-treestatus (@garbas)
- [x] shipit-bot-uplift (@La0)
- [x] shipit-code-coverage (@marco-c)
- [x] shipit-code-coverage-backend (@marco-c)
- [x] shipit-code-coverage-crawler (@marco-c)
- [x] shipit-frontend (@rail @garbas)
- [x] shipit-pulse-listener (@La0)
- [x] shipit-static-analysis (@La0)
- [x] shipit-uplift (@La0)

# Deployment to production

https://tools.taskcluster.net/groups/aBMDOJKsTOqsd4bwzO_kUw

## Production QA

- [x] releng-docs (@garbas)
- [x] releng-frontend (@garbas)
- [x] releng-mapper (@garbas)
- [x] releng-notification-identity (@garbas)
- [x] releng-notification-policy (@garbas)
- [x] releng-tokens (@garbas)
- [x] releng-tooltool (@garbas)
- [x] releng-treestatus (@garbas)
- [x] shipit-bot-uplift (@La0)
- [x] shipit-code-coverage (@marco-c)
- [x] shipit-code-coverage-backend (@marco-c)
- [x] shipit-code-coverage-crawler (@marco-c)
- [x] shipit-frontend (@rail @garbas)
- [x] shipit-pulse-listener (@La0)
- [x] shipit-static-analysis (@La0)
- [x] shipit-uplift (@La0)

### CODE REVIEW

**Comment by rail** [comment]
I submitted #1409 to fix the issue with shipit/frontend.

**Comment by La0** [comment]
I had to change several thing in the staging secret:

* Rename `shipit-static-analysis` section to `staticanalysis/bot`
* In section `shipit-pulse-listener`, rename the 2 SA hookId to `services-staging-staticanalysis/bot`

After checking that the new hook is trigerred, i deleted the previous one

**Comment by La0** [comment]
Code coverage backend is  OK, but the Taskcluster task is failing : https://tools.taskcluster.net/groups/AansDMT6Q3mBxth8F785fQ/tasks/AansDMT6Q3mBxth8F785fQ/runs/0/logs/public%2Flogs%2Flive.log

**Comment by La0** [comment]
Uplift Bot [looks good](https://tools.taskcluster.net/groups/SNfbrSYiQ6GMfOo7xKhREw/tasks/SNfbrSYiQ6GMfOo7xKhREw/runs/0/logs/public%2Flogs%2Flive.log) on staging, after #1418

**Pull request merged**
